[workspace]
authors = ["lnotspotl <lnotspotl@gmail.com>"]
channels = ["conda-forge"]
name = "tbai"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
gxx = "13.3.*"
sysroot_linux-64 = "2.34.*"
fmt = "10.1.*"
spdlog = "1.12.0.*"
cpp-argparse = "*"
eigen="3.3.7.*"
gtest="*"
nanobind="2.4.*"
yaml-cpp="*"
pinocchio="3.9.*"
cmake="3.30.*"
just = ">=1.42.4,<2"
glpk="5.0.*"
pip="*"
python="3.12.*"
glfw="*"
libgl-devel="*"

[feature.rust.dependencies]
rust="*"

[feature.python.dependencies]
pytorch = { version = "==2.7.0", build = "*cpu_generic*" }

[environments]
default = ["rust"]
test = ["python"]
python = ["python", "rust"]
