# tbai demos

sim_startup_time := "1.5"

# Show available commands
[group('utils')]
help:
    @just --list

# Install Python dependencies
[group('utils')]
install_requirements:
    pip3 install -r ./requirements.txt

# Run G1 MuJoCo demo
[group('examples')]
g1_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path g1) &
    sleep {{sim_startup_time}}
    python3 ./tbai_g1_mujoco/deploy_g1.py

# Run Go2 MuJoCo demo
[group('examples')]
go2_rl_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path go2) &
    sleep {{sim_startup_time}}
    python3 ./tbai_go2_mujoco/deploy_go2.py

# Run Go2 MPC MuJoCo demo
[group('examples')]
go2_mpc_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path go2) &
    sleep {{sim_startup_time}}
    python3 ./tbai_go2_mpc_mujoco/deploy_go2_mpc.py

# Run ANYmal B MPC MuJoCo demo
[group('examples')]
anymal_b_mpc_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path anymal_b) &
    sleep {{sim_startup_time}}
    python3 ./tbai_anymal_b_mpc_mujoco/deploy_anymal_mpc.py

# Run ANYmal C MPC MuJoCo demo
[group('examples')]
anymal_c_mpc_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path anymal_c) &
    sleep {{sim_startup_time}}
    python3 ./tbai_anymal_c_mpc_mujoco/deploy_anymal_mpc.py

# Run ANYmal D MPC MuJoCo demo
[group('examples')]
anymal_d_mpc_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path anymal_d) &
    sleep {{sim_startup_time}}
    python3 ./tbai_anymal_d_mpc_mujoco/deploy_anymal_mpc.py

# Run Spot MPC MuJoCo demo
[group('examples')]
spot_mpc_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path spot) &
    sleep {{sim_startup_time}}
    python3 ./tbai_spot_mpc_mujoco/deploy_spot_mpc.py

# Run Franka MuJoCo demo
[group('examples')]
franka_mujoco_demo:
    #!/usr/bin/env bash
    trap 'kill 0' EXIT
    XDG_SESSION_TYPE=x11 tbai_mujoco $(python3 -m tbai_mujoco_descriptions.print_config_path franka_panda) &
    sleep {{sim_startup_time}}
    python3 ./tbai_franka_mujoco/deploy_franka.py --camera
